In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
book = pd.read_csv("data/BX-books.csv",sep=";", on_bad_lines='skip',encoding='latin-1')

C:\Users\Fakhur ali\AppData\Local\Temp\ipykernel_54484\2998565206.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  book = pd.read_csv("data/BX-books.csv",sep=";", on_bad_lines='skip',encoding='latin-1')

In [3]:
book.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
book.shape

(271360, 8)

In [5]:
book.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [6]:
book.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [7]:
book = book[['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
      'Image-URL-L']]

In [8]:
book.head(2)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...

In [9]:
book.rename(columns={
    "Book-Title" : "title",
    "Book-Author": "author",
    "Year-Of-Publication": "year",
    "Image-URL-L": "img_url"},inplace=True)

In [10]:
book.columns

Index(['ISBN', 'title', 'author', 'year', 'Publisher', 'img_url'], dtype='object')

In [11]:
book.head(2)

,ISBN,title,author,year,Publisher,img_url
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...

now working on new file bx-user

In [12]:
users = pd.read_csv("data/BX-users.csv",sep=";", on_bad_lines='skip',encoding='latin-1')

In [13]:
users.head(2)

   User-ID                   Location   Age
0        1         nyc, new york, usa   NaN
1        2  stockton, california, usa  18.0

In [14]:
users.shape

(278858, 3)

Ratings file

In [15]:
ratings = pd.read_csv("data/BX-book-ratings.csv",sep=";", on_bad_lines='skip',encoding='latin-1')

In [16]:
ratings.head(2)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5

In [17]:
ratings.shape

(1149780, 3)

In [18]:
print(book.shape)
print(users.shape)
print(ratings.shape)

(271360, 6)
(278858, 3)
(1149780, 3)

In [19]:
ratings.rename(columns={
    "User-ID" : "user_id",
    "Book-Rating" : "rating"},inplace=True)

In [20]:
ratings.head()

   user_id        ISBN  rating
0   276725  034545104X       0
1   276726  0155061224       5
2   276727  0446520802       0
3   276729  052165615X       3
4   276729  0521795028       6

In [21]:
ratings["user_id"].value_counts()

user_id
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...
119573        1
276706        1
276697        1
276679        1
276676        1
Name: count, Length: 105283, dtype: int64

In [22]:
ratings["user_id"].unique().shape

(105283,)

In [23]:
x=ratings["user_id"].value_counts() >200
x

user_id
11676      True
198711     True
153662     True
98391      True
35859      True
          ...
119573    False
276706    False
276697    False
276679    False
276676    False
Name: count, Length: 105283, dtype: bool

In [24]:
x[x].shape

(899,)

In [25]:
y = x[x].index
y

Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352, 110973,
       235105,
       ...
       116122,  44296,  28634,  59727,  73681, 274808, 188951,   9856, 155916,
       268622],
      dtype='int64', name='user_id', length=899)

In [26]:
ratings=ratings[ratings["user_id"].isin(y)]

In [27]:
ratings.head()

      user_id        ISBN  rating
1456   277427  002542730X      10
1457   277427  0026217457       0
1458   277427  003008685X       8
1459   277427  0030615321       0
1460   277427  0060002050       0

In [28]:
ratings.shape

(526356, 3)

In [29]:
ratings_with_book = ratings.merge(book, on = "ISBN")
ratings_with_book.head(3)

,user_id,ISBN,rating,title,author,year,Publisher,img_url
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...

In [30]:
num_rating = ratings_with_book.groupby('title')['rating'].count().reset_index()

In [31]:
num_rating.head(5)

                                               title  rating
0   A Light in the Storm: The Civil War Diary of ...       2
1                              Always Have Popsicles       1
2               Apple Magic (The Collector's series)       1
3   Beyond IBM: Leadership Marketing and Finance ...       1
4   Clifford Visita El Hospital (Clifford El Gran...       1

In [32]:
num_rating.rename(columns={'rating' : 'num_of_rating'},inplace=True)

In [33]:
num_rating.head()

                                               title  num_of_rating
0   A Light in the Storm: The Civil War Diary of ...              2
1                              Always Have Popsicles              1
2               Apple Magic (The Collector's series)              1
3   Beyond IBM: Leadership Marketing and Finance ...              1
4   Clifford Visita El Hospital (Clifford El Gran...              1

In [34]:
final_rating = ratings_with_book.merge(num_rating,on = 'title')
final_rating.head()

,user_id,ISBN,rating,title,author,year,Publisher,img_url,num_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...,7
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...,1
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...,1
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...,13

In [35]:
final_rating=final_rating[final_rating['num_of_rating']>50]
final_rating.head()

,user_id,ISBN,rating,title,author,year,Publisher,img_url,num_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82
13,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,133
15,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...,108
18,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,1995,HarperTorch,http://images.amazon.com/images/P/0061009059.0...,108
24,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,1998,HarperTrophy,http://images.amazon.com/images/P/006440188X.0...,79

In [36]:
final_rating.sample(10)

,user_id,ISBN,rating,title,author,year,Publisher,img_url,num_of_rating
187580,107784,0842329242,0,Nicolae: The Rise of Antichrist (Left Behind N...,Tim F. Lahaye,1998,Tyndale House Publishers,http://images.amazon.com/images/P/0842329242.0...,61
345484,198711,1551668998,0,Beach House,Mary Alice Monroe,2002,Mira,http://images.amazon.com/images/P/1551668998.0...,57
381953,223087,0345438329,5,Big Stone Gap: A Novel (Ballantine Reader's Ci...,Adriana Trigiani,2001,Ballantine Books,http://images.amazon.com/images/P/0345438329.0...,74
388488,225810,0449219364,0,G Is for Gumshoe (Kinsey Millhone Mysteries (P...,Sue Grafton,1991,Fawcett Books,http://images.amazon.com/images/P/0449219364.0...,82
235240,135149,0439139600,0,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,2002,Scholastic Paperbacks,http://images.amazon.com/images/P/0439139600.0...,125
147765,86641,0515127833,0,River's End,Nora Roberts,2003,Jove Books,http://images.amazon.com/images/P/0515127833.0...,77
203384,115002,0380778556,0,Rebecca,Daphne Du Maurier,1994,Avon,http://images.amazon.com/images/P/0380778556.0...,68
219829,127359,0670892963,0,Bridget Jones : The Edge of Reason,Helen Fielding,2000,Viking Books,http://images.amazon.com/images/P/0670892963.0...,53
475647,268032,0345386132,0,Eyes of a Child,Richard North Patterson,1996,Ballantine Books,http://images.amazon.com/images/P/0345386132.0...,51
329326,190708,0671670689,0,Dawn (Cutler),V.C. Andrews,1990,Pocket,http://images.amazon.com/images/P/0671670689.0...,56

In [37]:
final_rating.drop_duplicates(['user_id','title'],inplace=True)

In [38]:
final_rating.shape

(57952, 9)

In [39]:
book_pivot = final_rating.pivot_table(columns='user_id',index='title',values='rating')
book_pivot

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84 Charing Cross Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,7.0,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
book_pivot = book_pivot.sub(book_pivot.mean(axis=1), axis=0).fillna(0)

In [41]:
book_pivot

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,5.652778,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.000000,0.000000,0.0,-3.347222,0.0,0.0,0.000000,0.0
1st to Die: A Novel,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0
2nd Chance,0.000000,7.652174,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.000000,-2.347826,0.0,0.000000,0.0,0.0,-2.347826,0.0
4 Blondes,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,-0.971831,...,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0
84 Charing Cross Road,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.000000,0.000000,0.0,5.431373,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.000000,0.000000,0.0,3.779661,0.000000,0.0,0.0,0.0,3.779661,0.000000,...,0.0,0.0,0.000000,0.000000,0.0,-3.220339,0.0,0.0,0.000000,0.0
You Belong To Me,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.000000,0.000000,0.0,0.000000,-1.919355,0.0,0.0,0.0,0.000000,-1.919355,...,0.0,0.0,0.000000,0.000000,0.0,-1.919355,0.0,0.0,0.000000,0.0
Zoya,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0
"\O\"" Is for Outlaw""",0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,6.030612,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0

######### including new library scipy

In [42]:
from scipy.sparse import csr_matrix

In [43]:
book_sparse = csr_matrix(book_pivot)

In [44]:
book_sparse

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 57949 stored elements and shape (703, 888)>

In [45]:
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(n_components=100, random_state=42)
book_reduced = svd.fit_transform(book_sparse)
print("Before SVD:", book_sparse.shape)
print("After SVD:", book_reduced.shape)

Before SVD: (703, 888)
After SVD: (703, 100)

In [46]:
from sklearn.neighbors import NearestNeighbors as nn

In [47]:
model = nn(metric='cosine', algorithm='brute')

In [48]:
model.fit(book_reduced)

NearestNeighbors(algorithm='brute', metric='cosine')

In [49]:
# Transform this book’s vector using the SVD model before finding neighbors
book_vector = svd.transform(book_pivot.iloc[237,:].values.reshape(1,-1))
distance, suggestion = model.kneighbors(book_vector, n_neighbors=6)

In [50]:
distance

array([[2.22044605e-16, 3.49272793e-01, 4.79979856e-01, 5.05940067e-01,
        5.32308982e-01, 5.38256437e-01]])

In [51]:
suggestion

array([[237,  61, 208, 296, 286, 345]])

In [52]:
for i in range(len(suggestion)):
    print(book_pivot.index[suggestion[i]])

Index(['Hemlock Bay', 'Beach House',
       'Full Tilt (Janet Evanovich's Full Series)', 'Last Man Standing',
       'Key of Knowledge (Key Trilogy (Paperback))', 'Nerd in Shining Armor'],
      dtype='object', name='title')

In [53]:
book_pivot.index[3]

'4 Blondes'

In [54]:
books_name = book_pivot.index

In [55]:
import pickle
pickle.dump(model , open('artifacts/model.pkl' , 'wb'))
pickle.dump(books_name , open('artifacts/books_name.pkl' , 'wb'))
pickle.dump(final_rating , open('artifacts/final_rating.pkl' , 'wb'))
pickle.dump(book_pivot , open('artifacts/book_pivot.pkl' , 'wb'))
pickle.dump(svd, open('artifacts/svd.pkl', 'wb'))

In [56]:
def recommend_book(book_name):
    book_id = np.where(book_pivot.index == book_name)[0][0]
    book_vector = svd.transform(book_pivot.iloc[book_id, :].values.reshape(1, -1))
    distance, suggestion = model.kneighbors(book_vector, n_neighbors=6)

    for i in range(len(suggestion)):
        books = book_pivot.index[suggestion[i]]
        for j in books:
            print(j)

In [57]:
book_name= 'Hemlock Bay'

recommend_book(book_name)

Hemlock Bay
Beach House
Full Tilt (Janet Evanovich's Full Series)
Last Man Standing
Key of Knowledge (Key Trilogy (Paperback))
Nerd in Shining Armor

In [58]:
book_name= "Pride and Prejudice"

recommend_book(book_name)

Pride and Prejudice
Five Quarters of the Orange
White Teeth: A Novel
Rising Sun
Animal Farm
How to Be Good